name: aeroot
description: A place for all the DApps to live.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+245

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  core:
    path: packages/core

  core_ui:
    path: packages/core_ui

  aeuniverse:
    path: packages/aeuniverse

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
  flutter_native_splash: ^2.2.3

  # Hive is a lightweight and blazing fast key-value database written in pure Dart
  hive: ^2.2.1
  hive_flutter: ^1.1.0

  # A pure flutter toast library Support custom style/widget. Easy to use. You can use this library to achieve the same effect as Android toast
  oktoast: ^3.2.0

  # With the Flutter safe_device package, you can easily implement security steps such as Jailbroken, root, emulator and fake location detection.
  safe_device: ^1.1.1

dev_dependencies:
  flutter_lints: ^2.0.1
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  # Integration Tests
  #integration_test:
  #  sdk: flutter
  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl_generator: ^0.3.0
  # A command-line tool that create Msix installer from your flutter windows-build files.
  msix: ^3.5.1

flutter_icons:
  android: true
  ios: true

msix_config:
  display_name: Archethic Wallet
  publisher_display_name: Archethic Foundation
  identity_name: testnet.archethic.net
  msix_version: 0.1.8.0
  icons_background_color: "#000000"
  logo_path: windows/icons/Icon-512.png
  # See https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations
  capabilities: "internetClient,webcam,USB,Bluetooth"
  output_name: ArchethicWallet

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
    - family: Equinox
      fonts:
        - asset: assets/fonts/Equinox Bold.otf
        - asset: assets/fonts/Equinox Regular.otf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true