name: aewallet
description: AE Wallet App
version: 0.2.3+203
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  core:
    path: ../core

  core_ui:
    path: ../core_ui

  aeuniverse:
    path: ../aeuniverse

  # Archethic dart library for Flutter based on Official Archethic Javascript library for Node and Browser
  archethic_lib_dart: ^1.0.13
  #archethic_lib_dart: 
  #  git:
  #    url: https://github.com/archethic-foundation/libdart.git
  #    ref: master
  
  # EventTaxi could be used to send events through different layers of the application decoupled from the architecture
  event_taxi: ^1.0.0

  # PhoenixSocket provides a feature-complete implementation of Phoenix Sockets, using a single API based on StreamChannels compatible with any deployment of Flutter.
  phoenix_socket: ^0.5.3
  gql_exec: ^0.4.0
  gql_link: ^0.4.2
  graphql_flutter: ^5.1.1-beta.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/icons/
    - assets/icons/txInfos/
    - assets/buy/
