name: core_ui
description: AE Core UI Lib
version: 0.2.3+203
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  core:
    path: ../core

  flutter:
    sdk: flutter

  # Archethic dart library for Flutter based on Official Archethic Javascript library for Node and Browser
  archethic_lib_dart: ^1.0.23
  #archethic_lib_dart: 
  #  git:
  #    url: https://github.com/archethic-foundation/libdart.git
  #    ref: master

  # Localization
  intl: ^0.17.0
  
dev_dependencies:
  flutter_lints: ^2.0.1
  # Automatically organize your dart imports
  import_sorter: ^4.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/themes/sapphire_blue/
    - assets/themes/dark/
    - assets/themes/emerald_green/
    - assets/themes/sea_green/
    - assets/themes/navy_blue/
    - assets/themes/honey_orange/
    - assets/themes/byzantine_violet/
    - assets/themes/fire_red/
    - assets/themes/pearl_grey/
