name: aeuniverse
description: AE Universe App
version: 0.2.3+203
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  aewallet:
    path: ../aewallet

  core:
    path: ../core

  core_ui:
    path: ../core_ui
    
  aeroot: 
    path: ../../

  # Beautiful animations inspired on Animate.css, every animation is a widget that contains default but customizable values that look attractive.
  animate_do: ^2.1.0

  # Archethic dart library for Flutter based on Official Archethic Javascript library for Node and Browser
  #archethic_lib_dart: ^1.0.23
  archethic_lib_dart: 
    git:
      url: https://github.com/archethic-foundation/libdart.git
      ref: master

  # Flutter widget that automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^3.0.0

  # A flutter plugin for scanning 2D barcodes and QRCodes via camera
  barcode_scan2: ^4.2.1

  # Bottom bar helps create an optimized bottom navigation bar with beautiful animations
  bottom_bar: ^2.0.2

  # Collections and utilities functions and classes related to collections.
  collection: ^1.16.0

  # Encapsulates TabController, TabBar and TabBarView into a single customizable Widget.
  contained_tab_bar_view: ^0.8.0

  # Utilities for converting between data representations. Provides a number of Sink, Codec, Decoder, and Encoder types
  convert: ^3.0.2

  # EventTaxi could be used to send events through different layers of the application decoupled from the architecture
  event_taxi: ^1.0.0
  
  # A PageView widget adjusting it's height to currently displayed page
  expandable_page_view: 
    git:
      url: https://github.com/redDwarf03/expandable_page_view.git
      ref: main

  # A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart
  fl_chart: ^0.55.1
  
  # Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android
  flutter_secure_storage: ^5.1.0

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files
  flutter_svg: ^1.1.0

  # A Flutter plugin to vibrate the device
  flutter_vibrate: ^1.3.0

  flutter:
    sdk: flutter

  # The Font Awesome Icon pack available as set of Flutter Icons.
  font_awesome_flutter: ^10.1.0

  # PhoenixSocket provides a feature-complete implementation of Phoenix Sockets, using a single API based on StreamChannels compatible with any deployment of Flutter.
  phoenix_socket: ^0.5.3
  gql_exec: ^0.4.0
  gql_link: ^0.4.2
  graphql_flutter: ^5.1.1-beta.4
  
  # Hive is a lightweight and blazing fast key-value database written in pure Dart
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Localization
  intl: ^0.17.0

  # Quiver is a set of utility libraries for Dart that makes using many Dart libraries easier and more convenient, or adds additional functionality
  quiver: ^3.1.0

  # Ledger dart library for Flutter. This library aims to provide a easy way to communicate with Ledger devices.
  ledger_dart_lib: ^0.1.2

  # A pure flutter toast library Support custom style/widget. Easy to use. You can use this library to achieve the same effect as Android toast
  oktoast: ^3.2.0

  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes
  url_launcher: ^6.1.5

  # String validation and sanitization for Dart
  validators: ^3.0.0
  
  # Yubico dart library for Dart/Flutter
  yubidart: ^1.0.3

dev_dependencies:
  flutter_lints: ^2.0.1
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/icons/
    - assets/icons/currency/
    - assets/icons/languages/
    - assets/icons/txInfos/