name: aeuniverse
description: AE Universe App
version: 0.2.3+203
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  aewallet:
    path: ../aewallet

  core:
    path: ../core

  core_ui:
    path: ../core_ui
    
  flutter:
    sdk: flutter

dev_dependencies:
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/icons/
    - assets/icons/currency/
    - assets/icons/txInfos/