name: core
description: AE Core Lib
version: 0.2.3+203
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  # Beautiful animations inspired on Animate.css, every animation is a widget that contains default but customizable values that look attractive.
  animate_do: ^2.1.0

  # Archethic dart library for Flutter based on Official Archethic Javascript library for Node and Browser
  archethic_lib_dart: ^1.0.17
  #archethic_lib_dart: 
  #  git:
  #    url: https://github.com/archethic-foundation/libdart.git
  #    ref: master
      
  # Flutter widget that automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^3.0.0

  # A flutter plugin for scanning 2D barcodes and QRCodes via camera
  barcode_scan2: ^4.2.1
  
  # Dart implementation of Bitcoin BIP39 Mnemonic code for generating deterministic keys
  bip39: ^1.0.6
  bip32: ^2.0.0

  # Utilities for converting between data representations. Provides a number of Sink, Codec, Decoder, and Encoder types
  convert: ^3.0.2

  # The decimal package allows you to deal with decimal numbers without losing precision
  decimal: ^2.2.0

  # A set of high-level APIs over PointyCastle for two-way cryptography.
  encrypt: ^5.0.1
  
  # EventTaxi could be used to send events through different layers of the application decoupled from the architecture
  event_taxi: ^1.0.0

  # A Flutter widget that can be expanded or collapsed by clicking on a header or an icon.
  expandable: ^5.0.1

  # A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart
  fl_chart: ^0.51.0
  
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android
  flutter_secure_storage: ^5.0.2

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files
  flutter_svg: ^1.1.0

  # A Flutter plugin to vibrate the device
  flutter_vibrate: ^1.3.0

  # The Font Awesome Icon pack available as set of Flutter Icons.
  font_awesome_flutter: ^10.1.0

  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App
  get_it: ^7.2.0

  # Hive is a lightweight and blazing fast key-value database written in pure Dart
  hive: ^2.2.1
  hive_flutter: ^1.1.0

  # A composable, multi-platform, Future-based API for HTTP requests
  http: ^0.13.4

  # Lazily load and display pages of items as the user scrolls down your screen.
  infinite_scroll_pagination: ^3.2.0

  # Localization
  intl: ^0.17.0

  # Ledger dart library for Flutter. This library aims to provide a easy way to communicate with Ledger devices.
  ledger_dart_lib: ^0.1.2
  #ledger_dart_lib: 
  #  git:
  #    url: https://github.com/redDwarf03/ledger_dart_lib.git
  #    ref: main

  # Flutter plugin for Android and iOS devices to allow local authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern
  local_auth: ^2.1.0

  # Flutter plugin for accessing the NFC features on Android and iOS.
  nfc_manager: ^3.1.1

  # A pure flutter toast library Support custom style/widget. Easy to use. You can use this library to achieve the same effect as Android toast
  oktoast: ^3.2.0

  # Flutter plugin for querying information about the application package, such as CFBundleVersion on iOS or versionCode on Android
  package_info_plus: ^1.4.2
  
  # A Dart library implementing cryptographic algorithms and primitives, modeled on the BouncyCastle library
  pointycastle: ^3.6.0
  
  # QR.Flutter is a Flutter library for simple and fast QR code rendering via a Widget or custom painter
  qr_flutter: ^4.0.0

  # Quiver is a set of utility libraries for Dart that makes using many Dart libraries easier and more convenient, or adds additional functionality
  quiver: ^3.1.0

  # With the Flutter safe_device package, you can easily implement security steps such as Jailbroken, root, emulator and fake location detection.
  safe_device: ^1.1.1

  # Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
  share_plus: ^4.0.7

  # A package to help you build highly customisable timelines with Flutter.
  timeline_tile: ^2.0.0

  # Tuple data structure
  tuple: ^2.0.0

  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes
  url_launcher: ^6.1.3
  
  # String validation and sanitization for Dart
  validators: ^3.0.0
  
  # Yubico dart library for Dart/Flutter
  yubidart: ^1.0.3

dev_dependencies:
  build_runner: ^2.1.11
  # A build system for Dart code generation and modular compilation
  hive_generator: ^1.1.3
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl_generator: ^0.3.0
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.2.0
  # A command-line tool that create Msix installer from your flutter windows-build files.
  msix: ^3.6.2

# The following section is specific to Flutter.
flutter:
