name: Build and Package Linux AppImage

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version

      - name: Setup Dependencies
        run: |
          sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libsecret-1-dev libjsoncpp-dev fuse gtk3

      - name: Build Flutter Application
        run: flutter build linux --release

      - name: Install appimage-builder
        run: |
          wget https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
          chmod +x appimage-builder-1.1.0-x86_64.AppImage

      - name: Generate AppImage
        run: |
          ./appimage-builder-1.1.0-x86_64.AppImage --recipe AppImageBuilder.yml

      - name: Upload AppImage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: appimage
          path: ./out/*.AppImage
